language: java

./gradlew assemble
./gradlew check

befor_cache: 
  -rm -f $HOME/.gradle/ceches/modules-2/modules-2.lock
  -rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    -$HOME/.gradle/caches/
    -$HOME/.gradle/wrapper/
